"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IVRFSubscriptionV2Plus__factory = exports.IVRFMigratableConsumerV2Plus__factory = exports.IVRFCoordinatorV2Plus__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IVRFCoordinatorV2Plus__factory_1 = require("./IVRFCoordinatorV2Plus__factory");
Object.defineProperty(exports, "IVRFCoordinatorV2Plus__factory", { enumerable: true, get: function () { return IVRFCoordinatorV2Plus__factory_1.IVRFCoordinatorV2Plus__factory; } });
var IVRFMigratableConsumerV2Plus__factory_1 = require("./IVRFMigratableConsumerV2Plus__factory");
Object.defineProperty(exports, "IVRFMigratableConsumerV2Plus__factory", { enumerable: true, get: function () { return IVRFMigratableConsumerV2Plus__factory_1.IVRFMigratableConsumerV2Plus__factory; } });
var IVRFSubscriptionV2Plus__factory_1 = require("./IVRFSubscriptionV2Plus__factory");
Object.defineProperty(exports, "IVRFSubscriptionV2Plus__factory", { enumerable: true, get: function () { return IVRFSubscriptionV2Plus__factory_1.IVRFSubscriptionV2Plus__factory; } });
