"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IVRFMigratableConsumerV2Plus__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "vrfCoordinator",
                type: "address",
            },
        ],
        name: "CoordinatorSet",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "vrfCoordinator",
                type: "address",
            },
        ],
        name: "setCoordinator",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IVRFMigratableConsumerV2Plus__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IVRFMigratableConsumerV2Plus__factory = IVRFMigratableConsumerV2Plus__factory;
IVRFMigratableConsumerV2Plus__factory.abi = _abi;
