"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfirmedOwnerWithProposal__factory = exports.ConfirmedOwner__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ConfirmedOwner__factory_1 = require("./ConfirmedOwner__factory");
Object.defineProperty(exports, "ConfirmedOwner__factory", { enumerable: true, get: function () { return ConfirmedOwner__factory_1.ConfirmedOwner__factory; } });
var ConfirmedOwnerWithProposal__factory_1 = require("./ConfirmedOwnerWithProposal__factory");
Object.defineProperty(exports, "ConfirmedOwnerWithProposal__factory", { enumerable: true, get: function () { return ConfirmedOwnerWithProposal__factory_1.ConfirmedOwnerWithProposal__factory; } });
