"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VRFCoordinatorV2_5Mock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var VRFCoordinatorV2_5Mock__factory_1 = require("./VRFCoordinatorV2_5Mock__factory");
Object.defineProperty(exports, "VRFCoordinatorV2_5Mock__factory", { enumerable: true, get: function () { return VRFCoordinatorV2_5Mock__factory_1.VRFCoordinatorV2_5Mock__factory; } });
