"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VRFV2PlusClient__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var VRFV2PlusClient__factory_1 = require("./VRFV2PlusClient__factory");
Object.defineProperty(exports, "VRFV2PlusClient__factory", { enumerable: true, get: function () { return VRFV2PlusClient__factory_1.VRFV2PlusClient__factory; } });
