/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as vrfvrSol from "./VRFVR.sol";
export { MatchManagement__factory } from "./MatchManagement__factory";
export { NFTManagement__factory } from "./NFTManagement__factory";
export { RandomNumber__factory } from "./RandomNumber__factory";
export { TournamentFactory__factory } from "./TournamentFactory__factory";
export { TournamentManagement__factory } from "./TournamentManagement__factory";
export { UserManagement__factory } from "./UserManagement__factory";
