"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserManagement__factory = exports.TournamentManagement__factory = exports.TournamentFactory__factory = exports.RandomNumber__factory = exports.NFTManagement__factory = exports.MatchManagement__factory = exports.vrfvrSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.vrfvrSol = __importStar(require("./VRFVR.sol"));
var MatchManagement__factory_1 = require("./MatchManagement__factory");
Object.defineProperty(exports, "MatchManagement__factory", { enumerable: true, get: function () { return MatchManagement__factory_1.MatchManagement__factory; } });
var NFTManagement__factory_1 = require("./NFTManagement__factory");
Object.defineProperty(exports, "NFTManagement__factory", { enumerable: true, get: function () { return NFTManagement__factory_1.NFTManagement__factory; } });
var RandomNumber__factory_1 = require("./RandomNumber__factory");
Object.defineProperty(exports, "RandomNumber__factory", { enumerable: true, get: function () { return RandomNumber__factory_1.RandomNumber__factory; } });
var TournamentFactory__factory_1 = require("./TournamentFactory__factory");
Object.defineProperty(exports, "TournamentFactory__factory", { enumerable: true, get: function () { return TournamentFactory__factory_1.TournamentFactory__factory; } });
var TournamentManagement__factory_1 = require("./TournamentManagement__factory");
Object.defineProperty(exports, "TournamentManagement__factory", { enumerable: true, get: function () { return TournamentManagement__factory_1.TournamentManagement__factory; } });
var UserManagement__factory_1 = require("./UserManagement__factory");
Object.defineProperty(exports, "UserManagement__factory", { enumerable: true, get: function () { return UserManagement__factory_1.UserManagement__factory; } });
