"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VRF__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var VRF__factory_1 = require("./VRF__factory");
Object.defineProperty(exports, "VRF__factory", { enumerable: true, get: function () { return VRF__factory_1.VRF__factory; } });
