/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vrfvrSol from "./VRFVR.sol";
export type { vrfvrSol };
export type { MatchManagement } from "./MatchManagement";
export type { NFTManagement } from "./NFTManagement";
export type { RandomNumber } from "./RandomNumber";
export type { TournamentFactory } from "./TournamentFactory";
export type { TournamentManagement } from "./TournamentManagement";
export type { UserManagement } from "./UserManagement";
